spring:
  application:
    name: SBMS-SignUp-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/Brand_Add
    username: postgres
    # password:   <-- remove or leave empty
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true   # shows SQL in logs

  sql:
    init:
      mode: always   # run schema/data.sql if present  
  boot :
    admin :
       client :
           url : http://localhost:1111/

eureka :
    client :
       service-url :
          defaultzone :  http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
server :
   port : 8082 