

spring:
  application:
    name: SBMS-Service-Registry
    
    
server :
 port: 8761
 
eureka :
 client :
  register-with-eureka : false
  
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
